"""empty message

Revision ID: 055ce4f74d25
Revises: f42d759f6ba9
Create Date: 2025-05-27 20:53:05.776446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055ce4f74d25'
down_revision = 'f42d759f6ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('unit')

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
