"""empty message

Revision ID: 2a55d5c4c648
Revises: 72bf37a9bea9
Create Date: 2025-05-24 16:02:55.039325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a55d5c4c648'
down_revision = '72bf37a9bea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'user_id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty_type', sa.Enum('EASY', 'MODERATE', 'HARD', name='difficultytype'), nullable=False))
        batch_op.drop_column('dificulty_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dificulty_type', postgresql.ENUM('EASY', 'MODERATE', 'HARD', name='difficultytype'), autoincrement=False, nullable=False))
        batch_op.drop_column('difficulty_type')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('collections')
    # ### end Alembic commands ###
