"""empty message

Revision ID: 4d0533c4f808
Revises: a22dc63ad970
Create Date: 2025-06-04 21:07:36.266062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0533c4f808'
down_revision = 'a22dc63ad970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergens', sa.Text(), nullable=True))

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('allergens')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_grams', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('total_grams')
        batch_op.drop_column('portions')

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergens', sa.TEXT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('allergens')

    # ### end Alembic commands ###
