"""empty message

Revision ID: 9649cd064fe0
Revises: 4d0533c4f808
Create Date: 2025-06-06 21:57:41.462415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9649cd064fe0'
down_revision = '4d0533c4f808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saturated_fat', sa.Float()))
        batch_op.add_column(sa.Column('sugars', sa.Float()))
        batch_op.add_column(sa.Column('fiber', sa.Float()))
        batch_op.add_column(sa.Column('salt', sa.Float()))
        batch_op.add_column(sa.Column('sodium', sa.Float()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('sodium')
        batch_op.drop_column('salt')
        batch_op.drop_column('fiber')
        batch_op.drop_column('sugars')
        batch_op.drop_column('saturated_fat')

    # ### end Alembic commands ###
